version: '3.7'

services:
  frontend:
    build:
      context: ../apps/frontend
      dockerfile: Dockerfile
    volumes:
      - ../apps/frontend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${FRONTEND_PORT}:${FRONTEND_PORT}
    environment:
      - PORT=${FRONTEND_PORT}
    command: npm run dev

  backend:
    build:
      context: ../apps/backend
      dockerfile: Dockerfile
    volumes:
      - ../apps/backend:/usr/src/app
      - /usr/src/app/node_modules
    ports:
      - ${BACKEND_PORT}:${BACKEND_PORT}
    environment:
      - PORT=${BACKEND_PORT}
    command: npm run start:dev
    depends_on:
      - postgres

  postgres:
    image: postgres:13
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
    ports:
      - ${DB_PORT}:${DB_PORT}
